# -*- coding: utf-8 -*-

import command
import repository
import repository_branch
import odoo_version
import base_module
import database
import database_type
import database_backup
import database_module
import db_filter
import environment
import environment_repository
import instance
import instance_host
import mailserver
import partner
import server
import server_change
import server_configuration
import server_configuration_command
import server_hostname
import server_repository
import server_service
import service
import service_command
import docker_image
import server_docker_image
import wizard
