# -*- coding: utf-8 -*-

{
    'name': u'Infrastructure',
    'version': '0.2.0',
    'description': u'Infrastructure Management',
    'category': u'base.module_category_knowledge_management',
    'author': u'Ingeniería Adhoc',
    'website': 'www.ingadhoc.com',
    'license': 'AGPL-3',
    'depends': [u'mail'],
    'data': [],
    'installable': True,
    'auto_install': False,
    'demo': [
        u'security/infrastructure_group.xml',
        u'view/server_hostname_view.xml',
        u'view/instance_host_view.xml',
        u'view/db_filter_view.xml',
        u'view/server_repository_view.xml',
        u'view/partner_view.xml',
        u'view/mailserver_view.xml',
        u'view/repository_view.xml',
        u'view/service_view.xml',
        u'view/environment_version_view.xml',
        u'view/environment_repository_view.xml',
        u'view/db_back_up_policy_view.xml',
        u'view/environment_view.xml',
        u'view/instance_view.xml',
        u'view/service_command_view.xml',
        u'view/repository_branch_view.xml',
        u'view/server_configuration_view.xml',
        u'view/server_change_view.xml',
        u'view/server_service_view.xml',
        u'view/database_type_view.xml',
        u'view/database_view.xml',
        u'view/server_view.xml',
        u'view/command_view.xml',
        u'view/server_configuration_command_view.xml',
        u'view/infrastructure_menuitem.xml',
        u'data/server_hostname_properties.xml',
        u'data/instance_host_properties.xml',
        u'data/db_filter_properties.xml',
        u'data/server_repository_properties.xml',
        u'data/partner_properties.xml',
        u'data/mailserver_properties.xml',
        u'data/repository_properties.xml',
        u'data/service_properties.xml',
        u'data/environment_version_properties.xml',
        u'data/environment_repository_properties.xml',
        u'data/db_back_up_policy_properties.xml',
        u'data/environment_properties.xml',
        u'data/instance_properties.xml',
        u'data/service_command_properties.xml',
        u'data/repository_branch_properties.xml',
        u'data/server_configuration_properties.xml',
        u'data/server_change_properties.xml',
        u'data/server_service_properties.xml',
        u'data/database_type_properties.xml',
        u'data/database_properties.xml',
        u'data/server_properties.xml',
        u'data/command_properties.xml',
        u'data/server_configuration_command_properties.xml',
        u'data/server_hostname_track.xml',
        u'data/instance_host_track.xml',
        u'data/db_filter_track.xml',
        u'data/server_repository_track.xml',
        u'data/partner_track.xml',
        u'data/mailserver_track.xml',
        u'data/repository_track.xml',
        u'data/service_track.xml',
        u'data/environment_version_track.xml',
        u'data/environment_repository_track.xml',
        u'data/db_back_up_policy_track.xml',
        u'data/environment_track.xml',
        u'data/instance_track.xml',
        u'data/service_command_track.xml',
        u'data/repository_branch_track.xml',
        u'data/server_configuration_track.xml',
        u'data/server_change_track.xml',
        u'data/server_service_track.xml',
        u'data/database_type_track.xml',
        u'data/database_track.xml',
        u'data/server_track.xml',
        u'data/command_track.xml',
        u'data/server_configuration_command_track.xml',
        # u'workflow/database_workflow.xml',
        # u'workflow/environment_workflow.xml',
        # u'workflow/instance_workflow.xml',
        # u'workflow/server_workflow.xml',
        u'security/ir.model.access.csv'
        ],
    }
